name       : yaru-theme
version    : 18.10.4
release    : 2
source     :
    - https://github.com/ubuntu/yaru/archive/18.10.4.tar.gz : 93f7ce8f1fd5805700159e2be72f392eb8c7f81baa20e8399acce592c7e058e5
license    :
    - CC-BY-SA-4.0
    - GPL-3.0-or-later
component  :
    - ^yaru-icon-theme : desktop.theme
    - ^yaru-gtk-theme : desktop.theme
summary    : Yaru default ubuntu theme
description: |
    Yaru is a theme entirely backed by the Ubuntu community
patterns   :
    - ^yaru-icon-theme : /usr/share/icons
    - ^yaru-gtk-theme : /usr/share/themes
builddeps  :
    - sassc
setup      : |
    %patch -p1 < $pkgfiles/0001-gnome-shell-fix-install-dir.patch

    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Nuke the things we don't need
    rm -fr $installdir/usr/share/glib-2.0
    rm -fr $installdir/usr/share/xsessions
    rm -fr $installdir/usr/share/sounds
    rm -fr $installdir/usr/share/wayland-sessions
    rm -fr $installdir/usr/share/themes/Yaru/gnome-shell/extensions/ubuntu-dock@ubuntu.com
    rmdir $installdir/usr/share/themes/Yaru/gnome-shell/extensions
