name       : yaru-theme
version    : 20.04.6
release    : 9
source     :
    - https://github.com/ubuntu/yaru/archive/20.04.6.tar.gz : 024bf3ef198b8bd242a898e6849e17f5f1733cecb7a00fb7ce884d70ff9814cb
license    :
    - CC-BY-SA-4.0
    - GPL-3.0-or-later
    - LGPL-2.1-only
    - LGPL-3.0-only
component  :
    - ^yaru-icon-theme : desktop.theme
    - ^yaru-gtk-theme : desktop.theme
summary    : Yaru default ubuntu theme
description: |
    Yaru is a theme entirely backed by the Ubuntu community
patterns   :
    - ^yaru-icon-theme : /usr/share/icons
    - ^yaru-gtk-theme : /usr/share/themes
builddeps  :
    - sassc
rundeps    :
    - ^yaru-gtk-theme :
        - gtk-engines
        - gtk2-engine-murrine
setup      : |
    %patch -p1 < $pkgfiles/0001-fix-gnome-shell-install-dir.patch
    %meson_configure \
        -Dsessions=false \
        -Dsounds=false
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Fix symbolic links
    rm -rf $installdir/usr/share/themes/*/gnome-shell
    ln -sv /usr/share/themes/Yaru/Yaru-shell/Yaru $installdir/usr/share/themes/Yaru/gnome-shell
    ln -sv /usr/share/themes/Yaru/Yaru-shell/Yaru-dark $installdir/usr/share/themes/Yaru-dark/gnome-shell

    # Nuke the things we don't need
    rm -rf $installdir/usr/share/themes/Yaru/unity
