name       : yaru-theme
version    : 19.10.4
release    : 8
source     :
    - https://github.com/ubuntu/yaru/archive/19.10.4.tar.gz : bff882ded3e9951d9c657eb60c34fe2d4cf5b9b98751f63fb062c64a98d08fd1
license    :
    - CC-BY-SA-4.0
    - GPL-3.0-or-later
component  :
    - ^yaru-icon-theme : desktop.theme
    - ^yaru-gtk-theme : desktop.theme
summary    : Yaru default ubuntu theme
description: |
    Yaru is a theme entirely backed by the Ubuntu community
patterns   :
    - ^yaru-icon-theme : /usr/share/icons
    - ^yaru-gtk-theme : /usr/share/themes
builddeps  :
    - sassc
rundeps    :
    - ^yaru-gtk-theme :
        - gtk-engines
        - gtk2-engine-murrine
setup      : |
    %patch -p1 < $pkgfiles/0001-gnome-shell-fix-install-dir.patch

    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Nuke the things we don't need
    rm -fr $installdir/usr/share/glib-2.0
    rm -fr $installdir/usr/share/xsessions
    rm -fr $installdir/usr/share/sounds
    rm -fr $installdir/usr/share/wayland-sessions
    rm -fr $installdir/usr/share/themes/Yaru/gnome-shell/extensions/ubuntu-dock@ubuntu.com
    rmdir $installdir/usr/share/themes/Yaru/gnome-shell/extensions
