name       : yaru-theme
version    : 19.04.1
release    : 6
source     :
    - https://github.com/ubuntu/yaru/archive/19.04.1.tar.gz : 1be0954421b934c8381a0b87ff356c9d3daa7eb4545ef6c812cf739d1b373266
license    :
    - CC-BY-SA-4.0
    - GPL-3.0-or-later
component  :
    - ^yaru-icon-theme : desktop.theme
    - ^yaru-gtk-theme : desktop.theme
summary    : Yaru default ubuntu theme
description: |
    Yaru is a theme entirely backed by the Ubuntu community
patterns   :
    - ^yaru-icon-theme : /usr/share/icons
    - ^yaru-gtk-theme : /usr/share/themes
builddeps  :
    - sassc
setup      : |
    %patch -p1 < $pkgfiles/0001-gnome-shell-fix-install-dir.patch

    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Nuke the things we don't need
    rm -fr $installdir/usr/share/glib-2.0
    rm -fr $installdir/usr/share/xsessions
    rm -fr $installdir/usr/share/sounds
    rm -fr $installdir/usr/share/wayland-sessions
    rm -fr $installdir/usr/share/themes/Yaru/gnome-shell/extensions/ubuntu-dock@ubuntu.com
    rmdir $installdir/usr/share/themes/Yaru/gnome-shell/extensions
