name       : yaru-theme
version    : 22.10.2
release    : 18
source     :
    - https://github.com/ubuntu/yaru/archive/refs/tags/22.10.2.tar.gz : f6eb4532b6941ec9a21f9e7adbded62597c477e662f6c69a30cb62979561d730
license    :
    - CC-BY-SA-4.0
    - GPL-3.0-or-later
    - LGPL-2.1-only
    - LGPL-3.0-only
component  :
    - ^yaru-icon-theme : desktop.theme
    - ^yaru-gtk-theme : desktop.theme
summary    : Yaru default ubuntu theme
description: |
    Yaru is a theme entirely backed by the Ubuntu community
patterns   :
    - ^yaru-icon-theme : /usr/share/icons
    - ^yaru-gtk-theme :
        - /usr/share/themes
        - /usr/share/gtksourceview-*
builddeps  :
    - sassc
rundeps    :
    - ^yaru-gtk-theme :
        - gtk-engines
        - gtk2-engine-murrine
setup      : |
    %patch -p1 < $pkgfiles/0001-fix-gnome-shell-install-dir.patch
    %meson_configure \
        -Dsessions=false \
        -Dsounds=false
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Fix symbolic links
    rm -rf $installdir/usr/share/themes/*/gnome-shell
    ln -sv /usr/share/themes/Yaru/Yaru-shell/Yaru $installdir/usr/share/themes/Yaru/gnome-shell
    ln -sv /usr/share/themes/Yaru/Yaru-shell/Yaru-dark $installdir/usr/share/themes/Yaru-dark/gnome-shell

    # Nuke the things we don't need
    rm -rf $installdir/usr/share/themes/Yaru/unity
