name       : yaru-theme
version    : 23.10.0
release    : 22
source     :
    - https://github.com/ubuntu/yaru/archive/refs/tags/23.10.0.tar.gz : a157df472c241df132ef559e30b5a2f976f5f9963679b2e26a3d9ae0c46e7ece
license    :
    - CC-BY-SA-4.0  # icons/* sounds/*
    - GPL-3.0-or-later
    - LGPL-2.1-only # gnome-shell/upstream/theme/gnome-shell-sass/_common.scss
    - LGPL-3.0-only # icons/src/fullcolor/render-bitmaps.py icons/src/scalable/extract-symbolic-icons.rb
homepage   : https://github.com/ubuntu/yaru
component  :
    - ^yaru-icon-theme : desktop.theme
    - ^yaru-gtk-theme : desktop.theme
summary    : Yaru default ubuntu theme
description: |
    Yaru is a theme entirely backed by the Ubuntu community
patterns   :
    - ^yaru-icon-theme : /usr/share/icons
    - ^yaru-gtk-theme :
        - /usr/share/themes
        - /usr/share/gtksourceview-*
builddeps  :
    - sassc
rundeps    :
    - ^yaru-gtk-theme :
        - gtk-engines
        - gtk2-engine-murrine
setup      : |
    %patch -p1 < $pkgfiles/0001-fix-gnome-shell-install-dir.patch
    %meson_configure \
        -Dsessions=false \
        -Dsounds=false
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Fix symbolic links
    rm -rf $installdir/usr/share/themes/*/gnome-shell
    ln -sv /usr/share/themes/Yaru/Yaru-shell/Yaru $installdir/usr/share/themes/Yaru/gnome-shell
    ln -sv /usr/share/themes/Yaru/Yaru-shell/Yaru-dark $installdir/usr/share/themes/Yaru-dark/gnome-shell

    # Nuke the things we don't need
    rm -rf $installdir/usr/share/themes/Yaru/unity
